version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: underscore
    versions:
    - 1.12.1
